version: '3.7'

services:
  backend:
    image: service-image
    ports:
      - '5000:5000'

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
